excluded:
  - build
  - .git
  - scripts
  - ringcon-profiler
  - ringcon_profiler.swift
  - RingBreakTests

disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - legacy_random
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - yoda_condition

line_length:
  warning: 150
  error: 200

cyclomatic_complexity:
  warning: 16
  error: 25

type_body_length:
  warning: 850
  error: 1200

file_length:
  warning: 1250
  error: 1800

function_body_length:
  warning: 100
  error: 150

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - a
    - b
    - g
    - i
    - r
    - w
    - x
    - y
    - z
