excluded:
  - build
  - .git
  - scripts
  - ringcon-profiler
  - ringcon_profiler.swift
  - RingBreakTests

disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - legacy_random
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - yoda_condition

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 400
  error: 1000

file_length:
  warning: 600
  error: 1500

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - r
    - g
    - b
    - w
